### ISSUE TITLE
Bebop 2 mjpeg-stream not working

### ISSUE THREAD

**Issue by brunoua** [hybridgroup/node-bebop#26]
Hello,

I was trying to run the sample "mjpeg-stream" in my Beboop 2, however I encounter the following error:

/home/bruno/app/node_modules/node-bebop/lib/types.js:86
      return arg.enum[buffer.readInt32LE(index)].name;
                                                ^
TypeError: Cannot read property 'name' of undefined
    at Object.module.exports.enum.read (/home/bruno/app/node_modules/node-bebop/lib/types.js:86:49)
    at /home/bruno/app/node_modules/node-bebop/lib/bebop.js:330:18
    at Array.forEach (native)
    at Bebop._packetReceiver (/home/bruno/app/node_modules/node-bebop/lib/bebop.js:327:21)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)

Any suggestion?

Greetings,
Bruno Barbosa

**Comment by deadprogram** [comment]
Hi @brunoua we've just released v0.5.0 which has many improvements including the video command fixes, as you had already confirmed. Please give it a try, and if needed reopen this issue. Thanks!
